//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilesFolders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public string Regimen { get; set; }
        public int RegimenId1 { get; set; }
    
        public virtual Regimen RegimenId { get; set; }
    }
}
